//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KD.KFilter.Test {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KD.KFilter.Test.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 あいら
        ///あいみ 
        ///115252se
        ///11xp
        ///1234成人
        ///16dy图库
        ///16dy-图库
        ///18禁
        ///2008，小鹰号沉没
        ///222se图片
        ///2穴中出
        ///33bbb走光
        ///365qingse
        ///365青涩
        ///365青色
        ///3gpA片
        ///3P体验
        ///3P炮图 
        ///3s空间
        ///4P美眉艳图
        ///500wan专区
        ///5252se
        ///5252se.com
        ///55sss偷拍区
        ///5nxx
        ///77bbb
        ///77自拍
        ///77论坛
        ///78ai
        ///7se7dy
        ///88p干
        ///89风波
        ///8apao
        ///97ai
        ///97gan
        ///97se
        ///97sese
        ///97ss
        ///97xxoo
        ///97XXOO
        ///97干
        ///97色
        ///98bb
        ///999日本妹
        ///99bb
        ///99se
        ///99sel
        ///9nnnn
        ///a4u
        ///a4y
        ///acome
        ///adult
        ///Aiai Sakura  
        ///Aiba Rubi            
        ///Ai Fukai 
        ///Ai Hiyoshi 
        ///Aika Mayu 
        ///Aika Miura
        ///Aika Shimizu            
        ///Aika Yukino   
        ///Ai Kimijima [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string KEY {
            get {
                return ResourceManager.GetString("KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tandy Tang&apos;s Blog
        ///用我会的那些代码来改变我的人生
        ///博客园首页博问闪存新随笔联系订阅 管理 随笔-23  文章-0  评论-529 
        ///2013年，你得把自己当作一个好PM培养。
        ///
        ///　　时间过得真的很快，容不得你停下脚步去思考，你唯一可以做的就是努力、努力、在努力，不须扬鞭自奋蹄。感觉每个月都应该写点啥，记录下历史。作为阳历2013年的第一篇博客，说来也巧，今天正好是我生日，算是给自己的生日礼物吧。虽然农历2013新年还没来，但阳历2013已经过去一个月了。
        ///
        ///　　看标题，2013有两个任务：
        ///
        ///　　1)学习新技术，创新已学技术——温故而知新。
        ///
        ///　　2)要把自己努力向管理者方向培养，无论现在你是不是管理者，也无论你以后是否想成为一个好的PM。
        ///
        ///　　希望通过这篇博客与大家分享一下我的心得。如有不当之处，请忽略。本文适合工作1~2年开发者，大神们跳过。希望大家互相学习，共同进步，共创和谐社会。
        ///
        ///一、如何不断的学习新技术？
        ///
        ///　　新技术：其实就是之前自己不知道或者还没学过的技术。
        ///
        ///　　还记得我上一篇博客说过，我在2013年一定要弄一个移动开发出来，当然作为 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
    }
}
